---
title: "Machine Learning Project"
author: "Radisa Alpinah Priyanti"
date: "`r Sys.Date()`"
output: html_document
---

# **Introduction**
The goal of this project is to build a machine learning model to predict the manner in which a person performs a weightlifting exercise. The dataset comes from sensors placed on different parts of the body.

We will use the **Random Forest** algorithm, perform **cross-validation**, and estimate the **out-of-sample error**.

# **Loading Libraries**
```{r message=FALSE, warning=FALSE}
library(caret)
library(randomForest)
library(ggplot2)
train_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
test_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"

train_data <- read.csv(train_url)
test_data <- read.csv(test_url)
# Removing columns with too many missing values
na_counts <- colSums(is.na(train_data))
train_data <- train_data[, na_counts == 0]

# Removing irrelevant columns
train_data <- train_data[, -c(1:7)]
set.seed(123)
trainIndex <- createDataPartition(train_data$classe, p = 0.7, list = FALSE)
trainSet <- train_data[trainIndex, ]
testSet <- train_data[-trainIndex, ]
set.seed(123)
trainIndex <- createDataPartition(train_data$classe, p = 0.7, list = FALSE)
trainSet <- train_data[trainIndex, ]
testSet <- train_data[-trainIndex, ]
set.seed(123)
trainIndex <- createDataPartition(train_data$classe, p = 0.7, list = FALSE)
trainSet <- train_data[trainIndex, ]
testSet <- train_data[-trainIndex, ]
final_predictions <- predict(rf_model, test_data)
final_predictions
